service: page-renderer

frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221

functions:
  renderer:
    handler: lambda.handler
    timeout: 30
    events:
      - http:
          method: any
          path: /{proxy+}
          cors: true
